install:
  - source bootstrap.sh

before_script:
  - docker version
  - docker pull ubuntu:14.10

script:
  - docker run -d -p 9090:9090 ubuntu:14.04 /bin/nc -l 9090
  - nc -w 5 -z "$SLIRP_HOST" "9090"

notifications:
  email: false
