install:
  - source bootstrap.sh

before_script:
  - docker version
  - docker pull redis:latest

script:
  - docker run -d -p 6379:6379 redis:lastest
  - redis-cli info

notifications:
  email: false
