env:
  global:
    SLIRP_PORTS="6379"

install:
  - source bootstrap.sh

before_script:
  - docker version
  - docker pull redis:latest

script:
  - docker run --name=redis -d -p 6379:6379 redis:latest
  - docker ps
  - docker port redis
  - redis-cli info

notifications:
  email: false
